module.exports = [
    {
        title: 'Like This',
        artist: ['ØGM'],
        album: 'Like This - Single',
        albumCover: '/songs/ØGM-Like_This.jpeg',
        mp3: '/songs/ØGM-Like_This.mp3',
        genre: 'Electronic',
        songNum: '1',
        year: '2021',
        highlight: {
            start: '16',
            end: '37',
        },
    },{
        title: 'Love The Way You Lie',
        artist: ['Eminem', 'Rihanna'],
        album: 'Recovery',
        albumCover: '/songs/Eminem-Recovery.jpeg',
        mp3: '/songs/Eminem-Love_The_Way_You_Lie.mp3',
        genre: 'Pop',
        songNum: '15',
        year: '2010',
        highlight: {
            start: '11',
            end: '31',
        },
    },{
        title: 'Best Of You',
        artist: ['Foo Fighters'],
        album: 'In Your Honor',
        albumCover: '/songs/Foo_Fighters-In_Your_Honor.jpeg',
        mp3: '/songs/Foo_Fighters-Best_Of_You.mp3',
        genre: 'Rock',
        songNum: '3',
        year: '2005',
        highlight: {
            start: '0',
            end: '19',
        },
    },{
        title: `Comptine d'un autre été, l'après-midi`,
        artist: ['Yann Tiersen'],
        album: `Le Fabuleux destin d'Amélie Poulain`,
        albumCover: '/songs/Yann_Tiersen-Le_Fabuleux.jpeg',
        mp3: '/songs/Yann_Tiersen-Comptine.mp3',
        genre: 'Classical',
        songNum: '3',
        year: '2001',
        highlight: {
            start: '0',
            end: '18',
        },
    },{
        title: 'Sweather Weather',
        artist: ['The Neighbourhood'],
        album: 'I Love You',
        albumCover: '/songs/The_Neighbourhood-I-Love-You.jpeg',
        mp3: '/songs/The_Neighbourhood-Sweater_Weather.mp3',
        genre: 'Indie Rock',
        songNum: '4',
        year: '2013',
        highlight: {
            start: '14',
            end: '33',
        },
    },{
        title: 'Song 2',
        artist: ['Blur'],
        album: 'Blur (Special Edition)',
        albumCover: '/songs/Blur-Blur.jpeg',
        mp3: '/songs/Blur-Song_2.mp3',
        genre: 'Alternative Rock',
        songNum: '2',
        year: '1997',
        highlight: {
            start: '3',
            end: '21',
        },
    },{
        title: 'Innerbloom',
        artist: ['RÜFÜS DU SOL'],
        album: 'BLOOM',
        albumCover: '/songs/RÜFÜS_DU_SOL-BLOOM.jpeg',
        mp3: '/songs/RÜFÜS_DU_SOL-Innerbloom.mp3',
        genre: 'Electronic',
        songNum: '11',
        year: '2016',
        highlight: {
            start: '50',
            end: '70',
        },
    },{
        title: 'STAY',
        artist: ['The Kid LAROI', 'Justin Bieber'],
        album: 'STAY - Single',
        albumCover: '/songs/The_Kid_LAROI-STAY.jpeg',
        mp3: '/songs/The_Kid_LAROI-Stay.mp3',
        genre: 'Pop',
        songNum: '1',
        year: '2021',
        highlight: {
            start: '2',
            end: '22',
        },
    },{
        title: 'Sex on Fire',
        artist: ['Kings Of Leon'],
        album: 'Only By The Night',
        albumCover: '/songs/Kings_Of_Leon-Only-By-The-Night.jpeg',
        mp3: '/songs/Kings-of_Leon-Sex_On_Fire.mp3',
        genre: 'Rock',
        songNum: '3',
        year: '2008',
        highlight: {
            start: '80',
            end: '99',
        },
    },{
        title: `Beethoven's 5 Secrets`,
        artist: ['The Piano Guys'],
        album: 'The Piano Guys',
        albumCover: `/songs/The_Piano_Guys-The_Piano_Guys.jpeg`,
        mp3: `/songs/The_Piano_Guys-Beethoven's_5_Secrets.mp3`,
        genre: 'Classical',
        songNum: '4',
        year: '2013',
        highlight: {
            start: '26',
            end: '45',
        },
    },{
        title: 'R U Mine?',
        artist: ['Artic Monkeys'],
        album: 'AM',
        albumCover: '/songs/Artic_Monkeys-AM.jpeg',
        mp3: '/songs/Arctic_Monkeys-R_U_Mine.mp3',
        genre: 'Indie Rock',
        songNum: '2',
        year: '2013',
        highlight: {
            start: '0',
            end: '20',
        },
    },{
        title: 'Numb',
        artist: ['Linkin Park'],
        album: 'Meteora',
        albumCover: '/songs/Linkin_Park-METEORA.jpeg',
        mp3: '/songs/Linkin_Park-Numb.mp3',
        genre: 'Alternative Rock',
        songNum: '13',
        year: '2003',
        highlight: {
            start: '6',
            end: '25',
        },
    },
];